name: EasterEggs
version: ${project.version}
main: org.explorersbay.EasterEggs
api-version: 1.16
authors: [ ResourcesMCM ]
description: The easter eggs plugin for Explorer's Bay.
website: store.explorersbay.com
